-- AlterTable
ALTER TABLE "File" ALTER COLUMN "chunkEnd" SET DEFAULT '',
ALTER COLUMN "chunkEnd" SET DATA TYPE TEXT,
ALTER COLUMN "chunkStart" SET DEFAULT '',
ALTER COLUMN "chunkStart" SET DATA TYPE TEXT;
